# Generated by Django 4.2.3 on 2023-07-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('released', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
